### PR TITLE
Data-centric logic overhaul

### PR DESCRIPTION
**Pull request by jkingsman**
This is a big one - all calendar logic was overhauled to be data first, all appropriate tests were also overhauled and a couple were added. The change in master was just the prelude to this; this is where all the heavy lifting of backend change happened.

I cut out some big swaths of crufty js code and put in nice code referencing our data model - the changed paradigm really lends itself to writing nicer code.

### CODE REVIEW

**Comment by jkingsman** [comment]
This closes #40

**Comment by jkingsman** [comment]
One question I do have is if marking a class as complete without specifying a class should default to the first available non-blank class in the Satisfied By list (if it exists)?

**Comment by RyanLoringCooper** [comment]
Do you think there is a way to mark that the class which satisfies the checked off requirement is unspecified?

**Comment by jkingsman** [comment]
That's as it is now - you can mark a class as scheduled or completed without specifying a completing class -- it just doesn't display the completing class in any of the data display.

**Comment by RyanLoringCooper** [comment]
It takes a little while to load now, but it does work. serve.py says it canot find js/requirements.json or js/testing.js, but yet the website still works and those files are definitely there. I am going to merge because there aren't any errors I can find.

**Pull request merged**
