### PR TITLE
Scheduling tables fill with classes and look pretty good now.

### PR DESCRIPTION
**Pull request by RyanLoringCooper**
Just looking for approval.

### CODE REVIEW

**Comment by RyanLoringCooper** [comment]
@KyraWayne mentioned she wanted to make some decoration = none to make things line up better.

**Review by jkingsman — CHANGES_REQUESTED** [review]
Make sure you close your `<ul>`'s

**Comment by jkingsman** [comment]
I think setting the `col-md-3` class on each `<th>` will work to keep spacing consistent. If I'm understanding what @KyraWayne means, I think `td > ul {list-style: none;}` will take care of it (if that's not what you mean, I think that's a good idea anyway).

**Review by jkingsman — APPROVED** [review]

**Review by jkingsman — CHANGES_REQUESTED** [review]
Accidentally marked my changes as OK'd -- re-requesting the `</ul>` changes. Sorry haha

**Comment by RyanLoringCooper** [comment]
Thanks for clarification.

**Comment by RyanLoringCooper** [comment]
We should merge this before Tuesday because at this time master's calendar does not work.

**Comment by RyanLoringCooper** [comment]
Master broken in commit 795b1cf778e69e91ffd40178a15b96734d5a23ed which was a merge with table-branch before it was ready. The most recent commit in table-branch will fix master when merged. 

I'm looking for approval to merge on the most recent commit.

**Review by jkingsman — APPROVED** [review]

**Comment by jkingsman** [comment]
Strictly on functionality, looks good to me. Either now or as a future issue, let's add `class="col-md-3"` to each `<th>` and  `td > ul {list-style: none;}` to the CSS -- either way is fine, and this is merge-ready right now as long as an issue is made if you/Kyra don't do those premerge.

Once this branch is in, I'm going to do a big linting run through everything that will break all branches, so I want to make sure mine is the only one pending before I do that.

**Pull request merged**
