### PR TITLE
Add calendar

### PR DESCRIPTION
**Pull request by jkingsman**
This is ready to go but there are design considerations I'm going to move over to @KyraWayne - it's MVP of the calendar but I think it could look a bit better.

### CODE REVIEW

**Comment by jkingsman** [comment]
Could I have a review by @Pillager225 or @KyraWayne before I merge this, please?

**Comment by RyanLoringCooper** [comment]
I like it, but things get a little wacky when you add more than 4 classes to a timeslot. I think a scrolling container would solve that problem pretty well. I think I can do it, but does that fall under UI? Either way, I am still going to give it a go.

Also I have a question about line 36 in the cheatsheet. Why did you change it to be fa1 instead of f1? What is that referencing? 

Works great, needs help to look pretty.

**Comment by RyanLoringCooper** [comment]
Oh, actually do we as a team want the scrolly thing? Just looking for approval here.

**Comment by jkingsman** [comment]
Yeah that kinda bugged me about the expanding box - I'll see what I can do with that; I'm not a huge fan of scrolling and I know there's a neat way to do the expansion and keep the sub rows anchored. If I can get a quick fix I'll just slap it in (otherwise I'll let our designer kick that problem's ass :D).

RE: the naming, I realized Spring & Summer were both 'S', so I just extended the code that does the labels to include the first two letters of the season and amended all the code to work with that. Little clowny but it works ¯\_(ツ)_/¯

TYVM for the review!

**Comment by jkingsman** [comment]
Alright, I figured it out - just needed a margin depth hack. Things should work fine with as many classes as you want now; the whole row expands and the columns stay sticky on the bottom. Definitely need lots more prettifying by @KyraWayne but otherwise I think this is good.

I'm going to go ahead and merge now.

**Comment by RyanLoringCooper** [comment]
After the most recent edits, I am seeing the last row of the calendar stretch to the bottom, and the upper rows don't have nearly as much room. Also at the bottom of the page, wacko horizontal lines are in the calendar.  I attached a picture for reference. I am using firefox 49.0.2
capture

**Comment by jkingsman** [comment]
Oh snap good catch. I'll patch that now. Sorry!!

[shames self for breaking master]

**Comment by jkingsman** [comment]
Alright I've pushed a hotfix for that. I'll leave this one in @KyraWayne 's court; it's clearly a little beyond me haha.

**Comment by RyanLoringCooper** [comment]
1. That's what the tester is for!
2. No reason to apologize, it wasn't terrible.
3. I wouldn't say it is broken, just has unnecessary stuff and strange.
4. I really, really like this pull request thing and I wish I had used it before, but I feel like I am overusing the comment thingy and it creates unnecessary spam. Oh well, I could always unsubscribe.
5. Good fix. The calendar looks good even with 5 classes now, but more than that kinda breaks it like the old bug where only one time section would grow vertically. Luckily, I don't think it is common to take more than 5 classes. They would have to take a bunch of 2 or 1 unit courses, or have some special permission thingy to overload like crazy.

**Comment by jkingsman** [comment]
Yeah once you get your notification settings tweaked to your liking (I turn off email but get push notifications through CodeHub on my phone) it's a great system. Good way to organize and communicate  :D

Push comes to shove we can always kick the `min-height` out to bigger than the theoretical 'max' any sane person would take. I've opened issue #13 to address and kicked it over to Kyra for her to take a crack at it.

**Comment by jkingsman** [comment]
Also, with what I meant about breaking master - more of a colloquialism than actually broken. Master is ideally supposed to be 100% functional and clean at all times; incomplete feature branches wait in the wings until they're finished and approved, so having crap in master is kind of a cardinal sin.

**Pull request merged**
