### PR TITLE
Style changes to calender entries.

### PR DESCRIPTION
**Pull request by RyanLoringCooper**
I added class="col-md-3" to <th>s in the calender and made a new class for
the ul entries called cal-entry that set the list-style to none by following Jack's guidelines in issue #34 .

### CODE REVIEW

**Comment by jkingsman** [comment]
I'm AFK right now but if the width stays constant on the table cells when you add classes and they don't show up with the bullet points, let's pull the trigger 👍🏻

**Comment by RyanLoringCooper** [comment]
Naw, I want Kyra's contribution first.

**Comment by jkingsman** [comment]
Whoops didn't see the assignment; sounds like a plan

**Comment by jkingsman** [comment]
@KyraWayne, can we get this approved ASAP please? I'm planning on tagging our master release at 5PM, so whatever is in there at 5 is what we go with for tomorrow so that I can have time to test tonight.

**Comment by KyraWayne** [comment]
Have been making some minor tweaks. I will notify you once I am finished.

**Pull request merged**
