### PR TITLE
Add sharing functionality

### PR DESCRIPTION
**Pull request by jkingsman**

### CODE REVIEW

**Comment by jkingsman** [comment]
Hefty addon; to discuss at meeting.

**Comment by jkingsman** [comment]
Handles #22

**Comment by RyanLoringCooper** [comment]
Works great. Feel free to merge when comfortable, but preferably after Tuesday?

**Comment by jkingsman** [comment]
Sounds good.

**Comment by RyanLoringCooper** [comment]
There is a problem with the readonly well not displaying on my browser. I can show you at our 6 o'clock meeting. In addition, serve.py also has a error that I will fix and commit now.

**Comment by jkingsman** [comment]
Yeah we can check that out at the meeting but with where things are at I'm seeing this as a super low priority/no problem if it doesn't make it in -- I'd rather scrap this and have everything else locked in. I'm gonna fix serve.py on master btw.

**Comment by jkingsman** [comment]
I'm going to close this PR since I don't think we're doing this.

**Pull request closed without merging**
